services:
  db:
    image: postgres:16
    container_name: db-ids
    restart: always
    environment:
      POSTGRES_DB: ids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret99
    ports:
      - "15001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: