server:
  servlet:
    contextPath: /api

spring:
  main:
    allow-circular-references: true
  application:
    name: ids
  datasource:
    url: jdbc:postgresql://localhost:15001/ids
    username: postgres
    password: secret99
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create